### Summary
Concatination of raw csv files into 1 file

In [1]:
import numpy as np
import json
import pandas as pd
from datetime import datetime
from dateutil.parser import parse

In [2]:
f0 = "formatted-pre-1-result.csv"
f1 = "formatted-pre-1-nisan2019.csv"
f2 = "formatted-pre-1-mayis2019.csv" 
f3 = "formatted-pre-1-haziran2019.csv"

output_f = 'formatted-pre-1-months4.csv' 

path = "./data/new/"
df0 = pd.read_csv(path + f0, parse_dates = ["EventTime"])
df1 = pd.read_csv(path + f1, parse_dates = ["EventTime"])
df2 = pd.read_csv(path + f2, parse_dates = ["EventTime"])
df3 = pd.read_csv(path + f3, parse_dates = ["EventTime"])

In [9]:
df0.tail(2)

,MachineName,ServerProgID,ServerNodeName,SubscriptionName,SourceName,EventTime,EventTime_MS,Severity,Message,Quality,...,AckReq,ActiveTime,ActiveTime_MS,Cookie,ActorID,Attributes,Area,Status,Shelving,Priority
606530,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,47TI931A,2019-03-21 03:35:43,70539648,500,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C IOP,0,...,True,2019/03/21 03:35:43.000000000,70539648,10591992,NaN,"[4353,""FCS0102"",""47TI931A"",""PV"",690.9423,0,"""",...",FCS0102,1,0,NaN
606531,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48AI004,2019-03-21 03:35:30,-59460352,500,48AI004 48S-1 H2S PV = 0.00 %H2S IOP,0,...,True,2019/03/21 03:35:30.000000000,-59460352,10591992,NaN,"[4353,""SCS0122"",""48AI004"",""PV"",0.0,0,"""","""",0,""...",SCS0122,1,0,NaN

In [10]:
df1.tail(2)

,MachineName,ServerProgID,ServerNodeName,SubscriptionName,SourceName,EventTime,EventTime_MS,Severity,Message,Quality,...,AckReq,ActiveTime,ActiveTime_MS,Cookie,ActorID,Attributes,Area,Status,Shelving,Priority
1277116,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,47TI931A,2019-04-08 07:31:44,-129959936,500,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C IOP,0,...,True,2019/04/08 07:31:44.000000000,-129959936,10591992,NaN,"[4353,""FCS0102"",""47TI931A"",""PV"",690.9423,0,"""",...",FCS0102,1,0,NaN
1277117,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,47TI931A,2019-04-08 07:32:09,120040064,500,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C IOP,0,...,True,2019/04/08 07:32:09.000000000,120040064,10591992,NaN,"[4353,""FCS0102"",""47TI931A"",""PV"",690.9423,0,"""",...",FCS0102,1,0,NaN

In [11]:
df2.tail(2)

,ï»¿MachineName,ServerProgID,ServerNodeName,SubscriptionName,SourceName,EventTime,EventTime_MS,Severity,Message,Quality,...,AckReq,ActiveTime,ActiveTime_MS,Cookie,ActorID,Attributes,Area,Status,Shelving,Priority
1776437,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48TIC2026,2019-05-30 23:57:02,986637056,500,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.2 C VEL+...,192,...,True,2019-05-30 23:57:01.000,976637056,4497144,NaN,"[4354,""FCS0105"",""48TIC2026"",""PV"",-5.1540508270...",FCS0105,1,0,NaN
1776438,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48TIC2026,2019-05-30 23:57:31,1276637056,500,48TIC2026 E208 CKS TEMIZ MDEA PV = -4.9 C VEL-...,192,...,True,2019-05-30 23:57:29.000,1256637056,4497144,NaN,"[4354,""FCS0105"",""48TIC2026"",""PV"",-4.8593006134...",FCS0105,1,0,NaN

In [12]:
df3.tail(2)

,MachineName,ServerProgID,ServerNodeName,SubscriptionName,SourceName,EventTime,EventTime_MS,Severity,Message,Quality,...,AckReq,ActiveTime,ActiveTime_MS,Cookie,ActorID,Attributes,Area,Status,Shelving,Priority
1845689,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48TIC2026,2019-06-20 22:59:21,-1500450176,500,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.0 C VEL+,192,...,True,2019/06/20 22:59:21.000000000,-1500450176,4497144,NaN,"[4353,""FCS0105"",""48TIC2026"",""PV"",-4.9545543193...",FCS0105,1,0,NaN
1845690,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48TIC2026,2019-06-20 22:58:50,-1810450176,500,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.1 C VEL+,192,...,True,2019/06/20 22:58:50.000000000,-1810450176,4497144,NaN,"[4353,""FCS0105"",""48TIC2026"",""PV"",-5.1051545143...",FCS0105,1,0,NaN

In [7]:
df = pd.concat([df0,df1, df2, df3], ignore_index=True)
df.to_csv( path + output_f, index=False)
df

,MachineName,ServerProgID,ServerNodeName,SubscriptionName,SourceName,EventTime,EventTime_MS,Severity,Message,Quality,...,ActiveTime,ActiveTime_MS,Cookie,ActorID,Attributes,Area,Status,Shelving,Priority,ï»¿MachineName
0,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48FIX2040,2019-03-11 05:09:04,1720164352,500,48FIX2040 C206'DAN C4'E A.GAZ CPV = -1 m3/h IO...,192,...,2019/03/11 05:09:02.000000000,1700164352,10591992,NaN,"[4354,""FCS0105"",""48FIX2040"",""CPV"",-1.309888768...",FCS0105,1,0,NaN,NaN
1,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,47TI931A,2019-03-11 05:09:24,1920164352,500,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C I...,192,...,2019/03/11 05:09:08.000000000,1760164352,10591992,NaN,"[4354,""FCS0102"",""47TI931A"",""PV"",690.9423,0,"""",...",FCS0102,1,0,NaN,NaN
2,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48TIC2027,2019-03-11 05:09:36,2040164352,500,48TIC2027 E209 CIKIS REJEN DRAM PV = -6.0 C IO...,192,...,2019/03/11 05:09:31.000000000,1990164352,10591992,NaN,"[4354,""FCS0105"",""48TIC2027"",""PV"",-6.0241699218...",FCS0105,1,0,NaN,NaN
3,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,47TI931A,2019-03-11 05:08:54,1620164352,500,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C I...,192,...,2019/03/11 05:08:48.000000000,1560164352,10591992,NaN,"[4354,""FCS0102"",""47TI931A"",""PV"",690.9423,0,"""",...",FCS0102,1,0,NaN,NaN
4,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,47TI931A,2019-03-11 05:08:36,1440164352,500,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C I...,192,...,2019/03/11 05:08:27.000000000,1350164352,10591992,NaN,"[4354,""FCS0102"",""47TI931A"",""PV"",690.9423,0,"""",...",FCS0102,1,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5505775,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,47TI931A,2019-06-20 22:55:55,734517120,500,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C IOP,0,...,2019/06/20 22:55:55.000000000,734517120,4497144,NaN,"[4353,""FCS0102"",""47TI931A"",""PV"",690.9423,0,"""",...",FCS0102,1,0,NaN,NaN
5505776,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48TIC2026,2019-06-20 22:58:52,-1790450176,500,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.4 C VEL-,192,...,2019/06/20 22:58:52.000000000,-1790450176,4497144,NaN,"[4353,""FCS0105"",""48TIC2026"",""PV"",-5.4251532554...",FCS0105,1,0,NaN,NaN
5505777,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48TIC2026,2019-06-20 22:58:57,-1740450176,500,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.3 C VEL-,192,...,2019/06/20 22:58:57.000000000,-1740450176,4497144,NaN,"[4353,""FCS0105"",""48TIC2026"",""PV"",-5.3174700736...",FCS0105,1,0,NaN,NaN
5505778,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48TIC2026,2019-06-20 22:59:21,-1500450176,500,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.0 C VEL+,192,...,2019/06/20 22:59:21.000000000,-1500450176,4497144,NaN,"[4353,""FCS0105"",""48TIC2026"",""PV"",-4.9545543193...",FCS0105,1,0,NaN,NaN
5505779,PHD47B,Yokogawa.ExaopcAECS1.1,STN0830,Yokogawa.ExaopcAECS1.1,48TIC2026,2019-06-20 22:58:50,-1810450176,500,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.1 C VEL+,192,...,2019/06/20 22:58:50.000000000,-1810450176,4497144,NaN,"[4353,""FCS0105"",""48TIC2026"",""PV"",-5.1051545143...",FCS0105,1,0,NaN,NaN

In [8]:
cols = ["MachineName","SourceName","EventTime", "Message","Quality","Condition","Mask","NewState","Status"]
df = pd.read_csv(path + output_f, usecols=cols ,parse_dates = ["EventTime"], low_memory=False)
df.to_csv( path + output_f, index=False)
df

,MachineName,SourceName,EventTime,Message,Quality,Condition,Mask,NewState,Status
0,PHD47B,48FIX2040,2019-03-11 05:09:04,48FIX2040 C206'DAN C4'E A.GAZ CPV = -1 m3/h IO...,192,IOP-,193,1,1
1,PHD47B,47TI931A,2019-03-11 05:09:24,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C I...,192,IOP,201,1,1
2,PHD47B,48TIC2027,2019-03-11 05:09:36,48TIC2027 E209 CIKIS REJEN DRAM PV = -6.0 C IO...,192,IOP-,201,1,1
3,PHD47B,47TI931A,2019-03-11 05:08:54,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C I...,192,IOP,201,1,1
4,PHD47B,47TI931A,2019-03-11 05:08:36,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C I...,192,IOP,201,1,1
...,...,...,...,...,...,...,...,...,...
5505775,PHD47B,47TI931A,2019-06-20 22:55:55,47TI931A C5 1.YTK GIRDISCAP SICAK PV = 691 C IOP,0,IOP,201,3,1
5505776,PHD47B,48TIC2026,2019-06-20 22:58:52,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.4 C VEL-,192,VEL-,193,3,1
5505777,PHD47B,48TIC2026,2019-06-20 22:58:57,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.3 C VEL-,192,VEL-,193,3,1
5505778,PHD47B,48TIC2026,2019-06-20 22:59:21,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.0 C VEL+,192,VEL+,193,3,1
5505779,PHD47B,48TIC2026,2019-06-20 22:58:50,48TIC2026 E208 CKS TEMIZ MDEA PV = -5.1 C VEL+,192,VEL+,193,3,1